language: node_js
node_js:
  - "6.4"
  - "6.3"
  - "5"
  - "4"
sudo: required
before_script:
  - npm config get prefix
  - mkdir ~/.npm-global
  - npm config set prefix '~/.npm-global'
  - echo 'export PATH=~/.npm-global/bin:$PATH' >> ~/.profile
  - source ~/.profile
  - npm link
  - git clone https://github.com/matrix-io/matrix-os.git ../
  - cd ../matrix-os/
  - npm install
  - lwd
